### ISSUE TITLE
vscode 1.46.0 版本也不支持。

### ISSUE THREAD

**Issue by xiaoningiscoming** [gamedilong/anes-repository#16]
![QQ截图20201014133110](https://user-images.githubusercontent.com/69829141/95947830-05910880-0e22-11eb-86a7-105cf39121bc.png)
不能install。

**Comment by gamedilong** [comment]
是的额，打包插件的时候，配的是支持到vscode版本 1.47.0+

**Comment by gamedilong** [comment]
刚打包了一个 0.0.3版本的，你下到本地装的试试。可以用的话，后面和其他的调整一起发布。
![image](https://user-images.githubusercontent.com/4177034/95948896-13e02400-0e24-11eb-863e-c041ef3d528e.png)
