### ISSUE TITLE
什么时候可以开放源码

### ISSUE THREAD

**Issue by QiuanLee** [gamedilong/anes-repository#17]

**Comment by gamedilong** [comment]
等稳定了，我再把代码整一整发上来，不发是因为写的太烂。你可以先看下jsnes这个项目，游戏模拟器用的这个，其他的工作就是和vscode整合的。

**Comment by QiuanLee** [comment]
好的，拿来学习学习

**Comment by oh-jy** [comment]
解压vsix 后研究了下，发现vscode 插件开发限制好多，和 web开发还是有差别。想加个全屏和屏幕显示内容放大，结果加不上。

**Comment by gamedilong** [comment]
开放了，有时间可以加加功能
