### ISSUE TITLE
游戏就一直在download

### ISSUE THREAD

**Issue by QiuanLee** [gamedilong/anes-repository#3]

**Comment by gamedilong** [comment]
用得第三方得资源链接，今天下的人有点多，下载不太稳定。这个要弄好，估计得自己搭cdn。可能要等一等。

**Comment by CCCpan** [comment]
想玩魂斗罗

**Comment by CCCpan** [comment]
都弯不了，一直下载.........

**Comment by CCCpan** [comment]
玩

**Comment by PiterYang** [comment]
一直在下载中。。。。

**Comment by gamedilong** [comment]
现在点下remote那的refresh下载还不行么，我自己搭静态的cdn最快也要到周末了,找的第三方的魂斗罗远程的资源那个模拟器不支持。可以加这个qq 858843908群，我尽快把能跑的资源放到群文件里面，通过本地加载玩。

**Comment by gamedilong** [comment]
关于下载的插件又发了一版，换了资源链接后，原来的下载方式有点问题。更新后重新refresh就可以了。
