### ISSUE TITLE
期望更多游戏加入

### ISSUE THREAD

**Issue by keepchen** [gamedilong/anes-repository#8]
#### 首先

感谢作者的付出，为大家提供了如此棒的游戏工具！

#### 其次

期望更多的游戏能加入，譬如：三国战纪、恐龙快打 等

#### 最后

再次表示大感谢～ :smile:

**Comment by gamedilong** [comment]
模拟器类型不同。恐龙快打，三国战纪这些街机的应该也有开源的js模拟器版本，后面找的试下。看能不能整进来
