### ISSUE TITLE
一个关于code-server上装这插件的有趣问题

### ISSUE THREAD

**Issue by jerry-yuan** [gamedilong/anes-repository#80]
把这插件装在code-server上,游戏实际运行在哪里?

**Comment by gamedilong** [comment]
在浏览器里面运行的应该，开发的时候是跑在vscode 的webview组件里面。这个版本的webview组件实际应该是本地的chrome内核，还是在浏览器里面跑的。

**Comment by jerry-yuan** [comment]
这就比较有意思了,所以说是直接用js撸的模拟器咯,我去爬爬代码,感谢大佬回复.

**Comment by jerry-yuan** [comment]
您好,插件是没有开源吗?我好像找不到插件的仓库,不过从插件解压出来发现了一个jsnes的库,应该就是这个做的了

**Comment by gamedilong** [comment]
嗯，用的jsnes。搜这个项目就行，就是集成到vscode里面去了。之前是准备开源的，一直没时间整理代码就搁置了。插件可以直接解压，代码也没有混淆可以直接看。

**Comment by jerry-yuan** [comment]
感谢您的回复,不过如果您时间上比较紧张,我还是建议您能够开源(如果您愿意的话),即使是开源未经整理的源码,这样的话感兴趣的人可以帮助给插件贡献一些代码.
